import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
// export interface PeriodicElement {
//   domainName: string;
// }

@Component({
  selector: 'app-display-campaign',
  templateUrl: './display-campaign.component.html',
  styleUrls: ['./display-campaign.component.css'],
})
export class DisplayCampaignComponent implements AfterViewInit {
  displayedColumns: string[] = ['domain'];
  dataSource = new MatTableDataSource<[]>(ELEMENT_DATA);

  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
  }
}

/**
 * @title Table with pagination
 */

const ELEMENT_DATA: any = [
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
  'media.net',
  'hello.in',
  'samsung.com',
  'flipkart.com',
  'forbes.com',
  'syska.in',
  ' cisco.org',
  'tinder.com',
];
